# Generated by Django 2.2.2 on 2021-04-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('parent_id', models.PositiveIntegerField(null=True)),
                ('amount', models.FloatField()),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
